### PR TITLE
added card.tsx and index.ts

### PR DESCRIPTION
**Pull request by sahandfarahani**

### CODE REVIEW

**Comment by ralph-dev** [comment]
Try fixing this merge conflict btw ^

**Comment by ralph-dev** [comment]
There is a merge conflict

**Comment by sahandfarahani** [comment]
> 
> 
> There is a merge conflict

This is actually the first PR which didn't work out well I made everything on PictureCard PR, this one should be deleted

**Comment by ralph-dev** [comment]
@sahandfarahani can you delete the branch the button is right here

**Pull request closed without merging**
