### PR TITLE
Moved Remaining Stories and Fixed Imports

### PR DESCRIPTION
**Pull request by arkiis**
Moved the rest of the stories from the stories folder and fixed imports/exports that were throwing errors.

### CODE REVIEW

**Review by ralph-dev — APPROVED** [review]
Lgtm

**Review by Ampatte2 — CHANGES_REQUESTED** [review]
Storybook doesn't build due to tsc errors. Errors need to be fixed for build to complete, or maybe add an ignore to .stories files?

@ralph-dev what do you think?

**Comment by ralph-dev** [comment]
Yeah that's alright, how many TSC issues are there can we not resolve them?

**Comment by Ampatte2** [comment]
Rough estimate 20-30. Ranging from type issues to unused variables to 'any' typing.

**Comment by arkiis** [comment]
> Rough estimate 20-30. Ranging from type issues to unused variables to 'any' typing.

Should the TS errors be fixed in this PR?

**Comment by Ampatte2** [comment]
@ralph-dev should errors be fixed or just ignore .stories.tsx?

**Review by williancozzi — APPROVED** [review]
lgtm

**Review by Ampatte2 — APPROVED** [review]
LGTM just double check with Ralph.

**Comment by arkiis** [comment]
@ralph-dev Should I merge this and open another PR to fix the TS errors?

**Comment by ralph-dev** [comment]
You can merge this

**Comment by ralph-dev** [comment]
The TS issues we can fix seperately

**Pull request merged**
