### PR TITLE
Cem 2595 info header try2

### PR DESCRIPTION
**Pull request by Hunterjdf**
Trying to make a new branch as the last one caused all of storybook to break on my end.

### CODE REVIEW

**Review by ralph-dev — APPROVED** [review]
Lgtm

**Comment by Hunterjdf** [comment]
Is there a delay on removing files via undo merge? 
Atm it seems that 
src/Containers/InfoHeader/InfoHeader.stories.tsx
src/Containers/InfoHeader/InfoHeader.tsx
are still in the main, preventing a new merge.

**Comment by ralph-dev** [comment]
> Is there a delay on removing files via undo merge? 
> 
> Atm it seems that 
> 
> src/Containers/InfoHeader/InfoHeader.stories.tsx
> 
> src/Containers/InfoHeader/InfoHeader.tsx
> 
> are still in the main, preventing a new merge. 

I would create a New branch from master and open a new PR to protect master

**Comment by Hunterjdf** [comment]
What would I do differently with the new branch compared to the one we are on now, that would protect the master? 
Or am I to do the new branch the exact same way I did this branch?

**Review by ralph-dev — APPROVED** [review]
Technically your fine I'm just worried about the merge conflicts if you'll have any. Would be safer to create a new branch from the latest master if you run into any issues during merging try it!

**Comment by Hunterjdf** [comment]
I created a new branch - Cem 2595 info header try3 
Will hold of on merging for now but it looks good. 
I also have the images on that page if you want to see them

**Comment by ralph-dev** [comment]
@Hunterjdf What's happening with this PR?

**Pull request closed without merging**
