### PR TITLE
Masked Input - Fix Final

### PR DESCRIPTION
**Pull request by Ampatte2**
Much much better UI/UX and useability:

Trying to figure out how to point people to the docs for react input mask for how to configure the mask, could do presets as well?

No longer need length

## $$$
Input Mask number

## Phone
Phone

### CODE REVIEW

**Comment by ralph-dev** [comment]
@Ampatte2 Can you take a video of toggling between Percentage and Amount

**Comment by Ampatte2** [comment]
## Multiple Masks
Multiple Masks

**Review by ralph-dev — APPROVED** [review]
LGTM

**Comment by ralph-dev** [comment]
Remove log from code and show a video before I can approve btw

**Comment by Ampatte2** [comment]
It just doesn't work, html events are always converted to strings, and getting this done it's going to just expose the value. Would be great if it could use the event but it cannot.

**Pull request merged**
