### PR TITLE
CEM-2598 [Oval Table Part 2]

### PR DESCRIPTION
**Pull request by Zhuk314**
Adjust the architecture of the oval table so that the chairs can be placed only on one side of the table.

### CODE REVIEW

**Comment by Zhuk314** [comment]
5left
4right
4top
5bottom

**Comment by Zhuk314** [comment]
4top
5bottom

**Comment by Zhuk314** [comment]
4right
5left

**Comment by ralph-dev** [comment]
Can we fix the circle table TSC issues

**Comment by Zhuk314** [comment]
Are you talking about failed checks? 
I was looking how to fix it, but I didn't find solution. 
It say `Error: Error: Unable to publish @cheapreats/react-ui v2.4.38 to NPM. `, and it appeared after I rename one magic number, so nothing major was change.

**Comment by ralph-dev** [comment]
Run "npx tsc"

**Comment by ralph-dev** [comment]
If you don't see any errors, merge master into your branch and run the command again

**Review by ralph-dev — APPROVED** [review]
Lgtm

**Pull request merged**
